export const data = [
    {
        question: "What is the objective of supervised learning?",
        option1: "a) Minimize error between predicted and actual output",
        option2: "b) Maximize reward based on actions taken",
        option3: "c) Cluster similar data points together",
        option4: "d) Discover hidden patterns in unlabeled data",
        ans: 1,
    },
    {
        question: "Which algorithm is commonly used for classification tasks in machine learning?",
        option1: "a) K-Means",
        option2: "b) Decision Trees",
        option3: "c) Principal Component Analysis (PCA)",
        option4: "d) Apriori",
        ans: 2,
    },
    {
        question: "What is the purpose of the activation function in a neural network?",
        option1: "a) To compute the error between predicted and actual output",
        option2: "b) To initialize the weights and biases of the network",
        option3: "c) To introduce non-linearity into the network",
        option4: "d) To perform dimensionality reduction",
        ans: 3,
    },
    {
        question: "Which technique is used to prevent overfitting in machine learning models?",
        option1: "a) Gradient Descent",
        option2: "b) Dropout",
        option3: "c) Feature Scaling",
        option4: "d) Bagging",
        ans: 2,
    },
    {
        question: "What is the purpose of cross-validation in machine learning?",
        option1: "a) To select the best model hyperparameters",
        option2: "b) To evaluate model performance on unseen data",
        option3: "c) To visualize high-dimensional data",
        option4: "d) To preprocess raw data",
        ans: 2,
    },
    {
        question: "In reinforcement learning, what is the agent's objective?",
        option1: "a) Minimize prediction error",
        option2: "b) Maximize immediate reward",
        option3: "c) Minimize training time",
        option4: "d) Maximize feature importance",
        ans: 2,
    },
    {
        question: "Which algorithm is used for finding the optimal policy in reinforcement learning?",
        option1: "a) Q-Learning",
        option2: "b) K-Nearest Neighbors",
        option3: "c) Linear Regression",
        option4: "d) Support Vector Machines (SVM)",
        ans: 1,
    },
    {
        question: "What is the purpose of dimensionality reduction techniques such as PCA?",
        option1: "a) To transform categorical variables into numerical variables",
        option2: "b) To reduce noise in the dataset",
        option3: "c) To visualize high-dimensional data",
        option4: "d) To decrease the number of features while preserving important information",
        ans: 4,
    },
    {
        question: "Which evaluation metric is commonly used for regression tasks?",
        option1: "a) Accuracy",
        option2: "b) Precision",
        option3: "c) Mean Squared Error (MSE)",
        option4: "d) F1 Score",
        ans: 3,
    },
    {
        question: "In unsupervised learning, what is the main goal?",
        option1: "a) To predict a target variable",
        option2: "b) To find hidden patterns or structures in data",
        option3: "c) To classify data points into predefined categories",
        option4: "d) To minimize error between predicted and actual output",
        ans: 2,
    }
];